### ISSUE TITLE
Adding the EurOBIS details to the readme

### ISSUE THREAD

**Issue by kmexter** [envri-fair/marine-eov-broker#27]
Hi
Hoping this is the right way to do this: the eurobis errdap endpoint needs to be added to the README ("The default erddap servers configured are the following (as of 2022-01-28):"). Please do this asap (otherwise the work we did was for nothing.....)

**Comment by tcarval** [comment]
Hello Katrina @kmexter , I just added EurOBIS ERDDAP in the README file
https://github.com/envri-fair/marine-eov-broker/blob/main/README.md
